### ISSUE TITLE
Updates needed

### ISSUE THREAD

**Issue by markhealey** [OpenF2/iOS-Container#1]
This iOS app needs a couple of updates. 

- [x] iOS 8 support
- [x] Reduce size of UIWebView margins 50% (currently `float margin = 8;`, should be `float margin = 4;`)
- [x] Change the background color of the app to be `#258bd0` or `[UIColor colorWithRed:0.145 green:0.545 blue:0.816 alpha:1]`
- [x] Replace F2 logo in top left corner with [this one](http://www.openf2.org/img/logo-mark-white-528x528.png). Retain existing size
- [x] In the `MainViewController.m`, update the quote AppManifest to include symbol Context: 

```
[_f2QuoteView setAppJSONConfig:@"[{\"appId\": \"com_openf2_examples_javascript_quote\",\"manifestUrl\": \"http://www.openf2.org/Examples/Apps\",\"name\": \"Quote\", \"context\":{\"symbol\":\"MSFT\"}}]"];
```

- [x] In the `F2AppView.m`, update Bootstrap 2.3.2 to Bootstrap 3 CSS.

```
http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
```

- [x] In the `F2AppView.m`, update jQuery to version 2.1.1
- [x] In the `F2AppView.m`, update F2 1.3.3 to the 1.4-wip version:

```
https://raw.githubusercontent.com/OpenF2/F2/1.4-wip/sdk/f2.min.js
```

- [x] In the `F2AppView.m` line 209, replace `span12` with `col-md-12`.
- [ ] In the `F2AppView.m` line 212 & 215, replace `<h2>` with `<h3>`

**Comment by markmanes** [comment]
These changes are done with some notes:
- The request to update F2 1.3.3 to 1.4-wip version looks to be done but it is pointing to this URL: https://cdnjs.cloudflare.com/ajax/libs/F2/1.4.0/f2.min.js
- The request to change h2 with h3  at line 212 & 215 couldn't be done as I couldn't find the code referenced. Lines 212 & 215 have nothing to do with this.
