### ISSUE TITLE
Reference to /f2.min.js is incorrect.

### ISSUE THREAD

**Issue by ryanolsen** [OpenF2/iOS-Container#3]
The file reference to https://raw.githubusercontent.com/OpenF2/F2/1.4-wip/sdk/f2.min.js in F2AppView/F2AppView.m is wrong and throws a 404 error. I believe the correct location should be https://github.com/OpenF2/F2/blob/1.4.1-wip/sdk/f2.min.js.

**Comment by MikeLeber117** [comment]
I have the fix but am unable to push to the repo.

**Comment by timburcham** [comment]
Hey Mike, could you make a pull request, and then admins can review from there?

**Comment by timburcham** [comment]
Eg, http://docs.openf2.org/#contribute-to-f2
https://help.github.com/articles/using-pull-requests

**Comment by MikeLeber117** [comment]
Opened a pull. Thanks for the info Tim.

**Comment by timburcham** [comment]
Hey there, could a fellow @OpenF2/owners or @OpenF2/contributors take a look at this and provide a peer review?

**Comment by MikeLeber117** [comment]
Code is now on master. @ryanolsen This should be fixed.
